import type { BankingMetricAccountSnapshot } from '../../types'

/**
 * 教学数据统一使用元保存；界面在第 03 章的口径对比中按“亿元”展示，避免把示例金额误读成真实经营数据。
 */
export const depositAccountSnapshots: BankingMetricAccountSnapshot[] = [
  {
    accountId: 'A001',
    snapshotDate: '2026-09-30',
    customerScope: 'individual',
    product: 'demand',
    branch: 'hangzhou',
    currency: 'CNY',
    status: 'active',
    balance: 26_000_000_000,
  },
  {
    accountId: 'A002',
    snapshotDate: '2026-09-30',
    customerScope: 'corporate',
    product: 'term',
    branch: 'hangzhou',
    currency: 'CNY',
    status: 'active',
    balance: 30_000_000_000,
  },
  {
    accountId: 'A003',
    snapshotDate: '2026-09-30',
    customerScope: 'small-business',
    product: 'negotiated',
    branch: 'hangzhou',
    currency: 'CNY',
    status: 'active',
    balance: 2_400_000_000,
  },
  {
    accountId: 'A004',
    snapshotDate: '2026-09-30',
    customerScope: 'corporate',
    product: 'margin',
    branch: 'shanghai',
    currency: 'CNY',
    status: 'active',
    balance: 1_700_000_000,
  },
  {
    accountId: 'A005',
    snapshotDate: '2026-09-30',
    customerScope: 'small-business',
    product: 'term',
    branch: 'hangzhou',
    currency: 'CNY',
    status: 'active',
    balance: 42_700_000_000,
  },
  {
    accountId: 'A006',
    snapshotDate: '2026-09-30',
    customerScope: 'individual',
    product: 'demand',
    branch: 'shanghai',
    currency: 'USD',
    status: 'active',
    balance: 9_000_000_000,
  },
  {
    accountId: 'A007',
    snapshotDate: '2026-09-30',
    customerScope: 'individual',
    product: 'demand',
    branch: 'hangzhou',
    currency: 'CNY',
    status: 'closed',
    balance: 1_000_000_000,
  },
  {
    accountId: 'A001',
    snapshotDate: '2026-09-29',
    customerScope: 'individual',
    product: 'demand',
    branch: 'hangzhou',
    currency: 'CNY',
    status: 'active',
    balance: 25_800_000_000,
  },
  {
    accountId: 'A002',
    snapshotDate: '2026-09-29',
    customerScope: 'corporate',
    product: 'term',
    branch: 'hangzhou',
    currency: 'CNY',
    status: 'active',
    balance: 29_800_000_000,
  },
  {
    accountId: 'A003',
    snapshotDate: '2026-09-29',
    customerScope: 'small-business',
    product: 'negotiated',
    branch: 'hangzhou',
    currency: 'CNY',
    status: 'active',
    balance: 2_400_000_000,
  },
  {
    accountId: 'A004',
    snapshotDate: '2026-09-29',
    customerScope: 'corporate',
    product: 'margin',
    branch: 'shanghai',
    currency: 'CNY',
    status: 'active',
    balance: 1_700_000_000,
  },
  {
    accountId: 'A005',
    snapshotDate: '2026-09-29',
    customerScope: 'small-business',
    product: 'term',
    branch: 'hangzhou',
    currency: 'CNY',
    status: 'active',
    balance: 42_700_000_000,
  },
  {
    accountId: 'A006',
    snapshotDate: '2026-09-29',
    customerScope: 'individual',
    product: 'demand',
    branch: 'shanghai',
    currency: 'USD',
    status: 'active',
    balance: 8_800_000_000,
  },
  {
    accountId: 'A007',
    snapshotDate: '2026-09-29',
    customerScope: 'individual',
    product: 'demand',
    branch: 'hangzhou',
    currency: 'CNY',
    status: 'closed',
    balance: 1_000_000_000,
  },
]
