import type { LineageEdge, LineageEvidence, LineageNode } from '../../types'
import { bindLineageProductionChain } from '../../features/lineage/production'
import { legacySchedulerVisualization } from './legacy-scheduling-system'
import { sqlTransformationVisualization } from './sql-and-transformation'

const sqlTransformation: LineageEvidence = {
  source: 'sql_transformation',
  detail: 'SQL 转换：SELECT / CASE 重新映射 order_status 后写入下游对象。',
}

const taskDependency: LineageEvidence = {
  source: 'task_dependency',
  detail: '任务依赖：下游任务等待上游任务成功后才消费结果。',
}

const metricDefinition: LineageEvidence = {
  source: 'metric_definition',
  detail: '指标定义：指标口径引用该对象中的 order_status 语义。',
}

const lineageNodes: LineageNode[] = [
  {
    id: 'ods-order',
    label: 'ODS.ORDER',
    layer: 'ODS',
    role: '原始订单来源',
    x: 90,
    y: 90,
    entityType: 'table',
  },
  {
    id: 'dwd-order-detail',
    label: 'DWD.ORDER_DETAIL',
    layer: 'DWD',
    role: '统一订单明细',
    x: 380,
    y: 90,
    entityType: 'table',
  },
  {
    id: 'dws-sales',
    label: 'DWS.SALES',
    layer: 'DWS',
    role: '销售主题汇总',
    x: 205,
    y: 245,
    entityType: 'table',
  },
  {
    id: 'dws-user',
    label: 'DWS.USER',
    layer: 'DWS',
    role: '用户主题汇总',
    x: 555,
    y: 245,
    entityType: 'table',
  },
  {
    id: 'ads-report',
    label: 'ADS.REPORT',
    layer: 'ADS',
    role: '经营分析报表',
    x: 380,
    y: 385,
    entityType: 'table',
  },
  {
    id: 'field-ods-order-status',
    label: 'ODS.ORDER.order_status',
    layer: 'ODS',
    role: '原始状态字段',
    x: 90,
    y: 90,
    entityType: 'field',
  },
  {
    id: 'field-dwd-order-status',
    label: 'DWD.ORDER_DETAIL.order_status',
    layer: 'DWD',
    role: '统一后的状态字段',
    x: 380,
    y: 90,
    entityType: 'field',
  },
  {
    id: 'field-dws-sales-status',
    label: 'DWS.SALES.status_group',
    layer: 'DWS',
    role: '销售状态分组',
    x: 205,
    y: 245,
    entityType: 'field',
  },
  {
    id: 'field-dws-user-status',
    label: 'DWS.USER.status_group',
    layer: 'DWS',
    role: '用户状态分组',
    x: 555,
    y: 245,
    entityType: 'field',
  },
  {
    id: 'field-ads-report-status',
    label: 'ADS.REPORT.status_summary',
    layer: 'ADS',
    role: '报表状态摘要',
    x: 380,
    y: 385,
    entityType: 'field',
  },
  {
    id: 'task-load-order',
    label: 'task.load_order',
    layer: 'TASK',
    role: '载入订单数据',
    x: 90,
    y: 90,
    entityType: 'task',
  },
  {
    id: 'task-build-order-detail',
    label: 'task.build_order_detail',
    layer: 'TASK',
    role: '生成统一明细',
    x: 380,
    y: 90,
    entityType: 'task',
  },
  {
    id: 'task-build-sales',
    label: 'task.build_sales',
    layer: 'TASK',
    role: '生成销售主题',
    x: 205,
    y: 245,
    entityType: 'task',
  },
  {
    id: 'task-build-user',
    label: 'task.build_user',
    layer: 'TASK',
    role: '生成用户主题',
    x: 555,
    y: 245,
    entityType: 'task',
  },
  {
    id: 'task-publish-report',
    label: 'task.publish_report',
    layer: 'TASK',
    role: '发布经营报表',
    x: 380,
    y: 385,
    entityType: 'task',
  },
  {
    id: 'metric-sales-status-rate',
    label: 'metric.sales_status_rate',
    layer: 'METRIC',
    role: '销售状态转化率',
    x: 205,
    y: 245,
    entityType: 'metric',
  },
  {
    id: 'metric-user-status-rate',
    label: 'metric.user_status_rate',
    layer: 'METRIC',
    role: '用户状态留存率',
    x: 555,
    y: 245,
    entityType: 'metric',
  },
  {
    id: 'metric-report-status',
    label: 'metric.report_status_summary',
    layer: 'METRIC',
    role: '报表状态摘要指标',
    x: 380,
    y: 385,
    entityType: 'metric',
  },
]

const lineageEdges: LineageEdge[] = [
  // Existing table-level graph. Keep this order to preserve the original BFS timeline.
  {
    source: 'ods-order',
    target: 'dwd-order-detail',
    relation: 'transform',
    evidence: sqlTransformation,
    confidence: 'confirmed',
  },
  {
    source: 'dwd-order-detail',
    target: 'dws-sales',
    relation: 'transform',
    evidence: sqlTransformation,
    confidence: 'confirmed',
  },
  {
    source: 'dwd-order-detail',
    target: 'dws-user',
    relation: 'transform',
    evidence: sqlTransformation,
    confidence: 'inferred',
  },
  {
    source: 'dws-sales',
    target: 'ads-report',
    relation: 'derives',
    evidence: metricDefinition,
    confidence: 'inferred',
  },
  {
    source: 'dws-user',
    target: 'ads-report',
    relation: 'derives',
    evidence: metricDefinition,
    confidence: 'inferred',
  },
  // Cross-entity path used by the field-change investigation.
  {
    source: 'field-dwd-order-status',
    target: 'task-build-order-detail',
    relation: 'consumes',
    evidence: taskDependency,
    confidence: 'confirmed',
  },
  {
    source: 'task-build-order-detail',
    target: 'dwd-order-detail',
    relation: 'transform',
    evidence: sqlTransformation,
    confidence: 'confirmed',
  },
  {
    source: 'dwd-order-detail',
    target: 'task-build-sales',
    relation: 'consumes',
    evidence: taskDependency,
    confidence: 'confirmed',
  },
  {
    source: 'dwd-order-detail',
    target: 'task-build-user',
    relation: 'consumes',
    evidence: taskDependency,
    confidence: 'confirmed',
  },
  {
    source: 'task-build-sales',
    target: 'dws-sales',
    relation: 'transform',
    evidence: sqlTransformation,
    confidence: 'confirmed',
  },
  {
    source: 'task-build-user',
    target: 'dws-user',
    relation: 'transform',
    evidence: sqlTransformation,
    confidence: 'confirmed',
  },
  {
    source: 'dws-sales',
    target: 'metric-sales-status-rate',
    relation: 'consumes',
    evidence: metricDefinition,
    confidence: 'confirmed',
  },
  {
    source: 'dws-user',
    target: 'metric-user-status-rate',
    relation: 'consumes',
    evidence: metricDefinition,
    confidence: 'confirmed',
  },
  {
    source: 'task-build-sales',
    target: 'field-dws-sales-status',
    relation: 'transform',
    evidence: sqlTransformation,
    confidence: 'confirmed',
  },
  {
    source: 'task-build-user',
    target: 'field-dws-user-status',
    relation: 'transform',
    evidence: sqlTransformation,
    confidence: 'confirmed',
  },
  {
    source: 'field-dws-sales-status',
    target: 'task-publish-report',
    relation: 'consumes',
    evidence: taskDependency,
    confidence: 'inferred',
  },
  {
    source: 'field-dws-user-status',
    target: 'task-publish-report',
    relation: 'consumes',
    evidence: taskDependency,
    confidence: 'inferred',
  },
  {
    source: 'task-publish-report',
    target: 'ads-report',
    relation: 'transform',
    evidence: sqlTransformation,
    confidence: 'confirmed',
  },
  {
    source: 'task-publish-report',
    target: 'field-ads-report-status',
    relation: 'transform',
    evidence: sqlTransformation,
    confidence: 'confirmed',
  },
  {
    source: 'field-ads-report-status',
    target: 'metric-report-status',
    relation: 'derives',
    evidence: metricDefinition,
    confidence: 'confirmed',
  },
  {
    source: 'metric-sales-status-rate',
    target: 'metric-report-status',
    relation: 'derives',
    evidence: metricDefinition,
    confidence: 'inferred',
  },
  {
    source: 'metric-user-status-rate',
    target: 'metric-report-status',
    relation: 'derives',
    evidence: metricDefinition,
    confidence: 'inferred',
  },
  // Same-entity paths make each view independently explorable.
  {
    source: 'field-ods-order-status',
    target: 'field-dwd-order-status',
    relation: 'transform',
    evidence: sqlTransformation,
    confidence: 'confirmed',
  },
  {
    source: 'field-dwd-order-status',
    target: 'field-dws-sales-status',
    relation: 'derives',
    evidence: sqlTransformation,
    confidence: 'confirmed',
  },
  {
    source: 'field-dwd-order-status',
    target: 'field-dws-user-status',
    relation: 'derives',
    evidence: sqlTransformation,
    confidence: 'inferred',
  },
  {
    source: 'field-dws-sales-status',
    target: 'field-ads-report-status',
    relation: 'derives',
    evidence: metricDefinition,
    confidence: 'inferred',
  },
  {
    source: 'field-dws-user-status',
    target: 'field-ads-report-status',
    relation: 'derives',
    evidence: metricDefinition,
    confidence: 'inferred',
  },
  {
    source: 'task-load-order',
    target: 'task-build-order-detail',
    relation: 'depends_on',
    evidence: taskDependency,
    confidence: 'confirmed',
  },
  {
    source: 'task-build-order-detail',
    target: 'task-build-sales',
    relation: 'depends_on',
    evidence: taskDependency,
    confidence: 'confirmed',
  },
  {
    source: 'task-build-order-detail',
    target: 'task-build-user',
    relation: 'depends_on',
    evidence: taskDependency,
    confidence: 'confirmed',
  },
  {
    source: 'task-build-sales',
    target: 'task-publish-report',
    relation: 'depends_on',
    evidence: taskDependency,
    confidence: 'inferred',
  },
  {
    source: 'task-build-user',
    target: 'task-publish-report',
    relation: 'depends_on',
    evidence: taskDependency,
    confidence: 'inferred',
  },
]

const lineageProductionGraph = bindLineageProductionChain({
  baseNodes: lineageNodes,
  baseEdges: lineageEdges,
  transformation: sqlTransformationVisualization,
  scheduler: legacySchedulerVisualization,
})

export const legacyLineageVisualization = {
  kind: 'lineage' as const,
  nodes: lineageProductionGraph.nodes,
  edges: lineageProductionGraph.edges,
  investigationEvent: lineageProductionGraph.investigationEvents[0],
  investigationEvents: lineageProductionGraph.investigationEvents,
}
