import type { LessonContent } from '../types'

export const starSchemaAndGrainContent: LessonContent = {
  eyebrow: '第 04 课 · 让事实表成为一颗星的星心',
  subtitle: '星型模型的重点不是画出漂亮的形状，而是看懂中央事件如何连接不同的分析角度。',
  quickSummary:
    '把事实表放在中央，点击周围维度追踪外键，再切换订单、订单明细和用户日三种 Grain，看见表结构与分析能力如何一起变化。',
  concept: {
    term: '星型模型与粒度',
    definition:
      '星型模型以事实表为中心、维度表为周边；粒度则定义事实表每一行代表的业务事件。粒度是事实字段设计和指标计算的起点。',
  },
  sections: [
    {
      kind: 'narrative',
      title: '先找中央的业务事件',
      paragraphs: [
        '一个商品被加入订单，是可以被记录、度量和聚合的业务事件。事实表保存这件事，用户、商品和店铺则提供观察它的不同角度。',
        '因此这节课不再从“拆一张大宽表”开始，而是直接从星心出发：点击一张表，查看它和事实表之间的关系。',
      ],
    },
    {
      kind: 'visualization',
      eyebrow: '拓扑实验 · 事实表在中央',
      title: '从中央事实表向外看',
      description:
        '选择一个节点或外键关系。被选中的维度会与 fact_order_item 一起高亮，帮助你把“星型”读成一组可追踪的连接。',
      visualization: {
        kind: 'star-schema',
        rawTable: {
          columns: [
            'order_id',
            'order_time',
            'user_id',
            'user_name',
            'user_city',
            'product_id',
            'product_name',
            'category',
            'shop_id',
            'shop_name',
            'quantity',
            'unit_price',
            'amount',
          ],
          rows: [
            {
              order_id: '1001',
              order_time: '2026-09-13 10:20',
              user_id: 'U01',
              user_name: '林夏',
              user_city: '杭州',
              product_id: 'P01',
              product_name: '保温杯',
              category: '家居',
              shop_id: 'S01',
              shop_name: '日常好物',
              quantity: 1,
              unit_price: 100,
              amount: 100,
            },
            {
              order_id: '1001',
              order_time: '2026-09-13 10:20',
              user_id: 'U01',
              user_name: '林夏',
              user_city: '杭州',
              product_id: 'P02',
              product_name: '帆布袋',
              category: '家居',
              shop_id: 'S01',
              shop_name: '日常好物',
              quantity: 2,
              unit_price: 100,
              amount: 200,
            },
            {
              order_id: '1002',
              order_time: '2026-09-13 11:05',
              user_id: 'U02',
              user_name: '周野',
              user_city: '上海',
              product_id: 'P03',
              product_name: '跑鞋',
              category: '运动',
              shop_id: 'S02',
              shop_name: '城市运动',
              quantity: 1,
              unit_price: 180,
              amount: 180,
            },
          ],
        },
        rawFieldGroups: [
          { id: 'order', label: '订单属性', tone: 'blue', fields: ['order_id', 'order_time'] },
          {
            id: 'user',
            label: '用户属性',
            tone: 'teal',
            fields: ['user_id', 'user_name', 'user_city'],
          },
          {
            id: 'product',
            label: '商品属性',
            tone: 'violet',
            fields: ['product_id', 'product_name', 'category'],
          },
          { id: 'shop', label: '店铺属性', tone: 'amber', fields: ['shop_id', 'shop_name'] },
          {
            id: 'measure',
            label: '交易事实',
            tone: 'navy',
            fields: ['quantity', 'unit_price', 'amount'],
          },
        ],
        tables: [
          {
            id: 'dim-user',
            name: 'dim_user',
            type: 'dimension',
            rowMeaning: '一个用户的当前属性记录',
            key: { label: '业务键', value: 'user_id' },
            fields: [
              { name: 'user_id', label: '用户标识', role: 'key' },
              { name: 'user_name', label: '用户名称', role: 'attribute' },
              { name: 'user_city', label: '用户城市', role: 'attribute' },
            ],
            responsibility: '描述“谁”参与了这笔交易，让事实可以按用户属性切分。',
          },
          {
            id: 'dim-product',
            name: 'dim_product',
            type: 'dimension',
            rowMeaning: '一个商品的描述属性记录',
            key: { label: '业务键', value: 'product_id' },
            fields: [
              { name: 'product_id', label: '商品标识', role: 'key' },
              { name: 'product_name', label: '商品名称', role: 'attribute' },
              { name: 'category', label: '商品分类', role: 'attribute' },
            ],
            responsibility: '描述“买了什么”，让销售额可以按商品和分类分析。',
          },
          {
            id: 'dim-shop',
            name: 'dim_shop',
            type: 'dimension',
            rowMeaning: '一个店铺的描述属性记录',
            key: { label: '业务键', value: 'shop_id' },
            fields: [
              { name: 'shop_id', label: '店铺标识', role: 'key' },
              { name: 'shop_name', label: '店铺名称', role: 'attribute' },
            ],
            responsibility: '描述“在哪个店铺发生”，让事实可以按店铺观察经营情况。',
          },
          {
            id: 'fact-order-item',
            name: 'fact_order_item',
            type: 'fact',
            rowMeaning: '一个订单中的一个商品',
            key: { label: '业务键', value: 'order_id + product_id（本例）' },
            fields: [
              { name: 'order_id', label: '订单标识', role: 'key' },
              { name: 'product_id', label: '商品标识', role: 'key' },
              { name: 'user_id', label: '用户外键', role: 'key' },
              { name: 'shop_id', label: '店铺外键', role: 'key' },
              { name: 'order_time', label: '下单时间', role: 'attribute' },
              { name: 'quantity', label: '购买数量', role: 'measure' },
              { name: 'unit_price', label: '商品单价', role: 'measure' },
              { name: 'amount', label: '商品金额', role: 'measure' },
            ],
            responsibility: '记录可加总的交易事实，并用外键连接用户、商品和店铺维度。',
          },
        ],
        grains: [
          {
            id: 'order',
            label: '订单粒度',
            statement: '一行 = 一个订单',
            description: '每一行已经把订单中的商品合并，amount 表示整笔订单金额。',
            columns: ['order_id', 'user_id', 'amount'],
            rows: [
              { order_id: '1001', user_id: 'U01', amount: 300 },
              { order_id: '1002', user_id: 'U02', amount: 180 },
            ],
            useCase: '适合回答订单数、订单金额、客单价等订单级问题。',
            boundary: '无法直接回答一个订单中分别购买了哪些商品。',
            recommended: false,
          },
          {
            id: 'order-item',
            label: '订单明细粒度',
            statement: '一行 = 一个订单中的一个商品',
            description: '每一行保留一个商品的数量和金额，是本案例推荐的基础事实粒度。',
            columns: ['order_id', 'product_id', 'quantity', 'amount'],
            rows: [
              { order_id: '1001', product_id: 'P01', quantity: 1, amount: 100 },
              { order_id: '1001', product_id: 'P02', quantity: 2, amount: 200 },
              { order_id: '1002', product_id: 'P03', quantity: 1, amount: 180 },
            ],
            useCase: '适合同时按订单、商品、用户和店铺拆解销售额。',
            boundary: '查询订单级指标时，要明确使用明细金额聚合，不能重复带入订单总额。',
            recommended: true,
          },
          {
            id: 'user-day',
            label: '用户日粒度',
            statement: '一行 = 一个用户一天的汇总',
            description: '每一行已经跨订单聚合，保留的是一天的订单数和金额。',
            columns: ['dt', 'user_id', 'order_count', 'amount'],
            rows: [{ dt: '2026-09-13', user_id: 'U01', order_count: 3, amount: 560 }],
            useCase: '适合用户日活跃、用户日消费和留存等上层汇总分析。',
            boundary: '已经丢失订单和商品明细，不适合作为最底层交易事实。',
            recommended: false,
          },
        ],
        errorDemo: {
          wrongColumns: ['order_id', 'product_id', 'order_total_amount'],
          wrongRows: [
            { order_id: '1001', product_id: 'A', order_total_amount: 300 },
            { order_id: '1001', product_id: 'B', order_total_amount: 300 },
          ],
          fixedColumns: ['order_id', 'product_id', 'item_amount'],
          fixedRows: [
            { order_id: '1001', product_id: 'A', item_amount: 100 },
            { order_id: '1001', product_id: 'B', item_amount: 200 },
          ],
          actualAmount: 300,
          wrongMeasure: 'order_total_amount',
          fixedMeasure: 'item_amount',
          wrongSql: 'SUM(order_total_amount)',
          fixedSql: 'SUM(item_amount)',
        },
      },
    },
    {
      kind: 'narrative',
      title: '粒度切换不是换一句描述',
      paragraphs: [
        '订单粒度压缩了商品细节，用户日粒度则进一步跨订单聚合。切换时，主键、示例行数和可以回答的问题都必须一起重新理解。',
        '当事实表的每一行代表一个商品时，order_total_amount 不能被复制到每一行；它必须改成与明细 Grain 对齐的 item_amount。',
      ],
    },
    {
      kind: 'takeaway',
      title: '读星型模型的三个问题',
      text: '先找中央事实，再沿外键看维度，最后确认一行代表什么。形状帮助你找到关系，粒度才保证数字正确。',
      bullets: [
        '事实表回答“发生了什么”。',
        '维度表回答“从哪个角度看”。',
        'Grain 决定“这一行到底是什么”。',
      ],
    },
    {
      kind: 'pitfall',
      title: '不要把中央事实表当成万能汇总表',
      text: '事实表粒度越细不代表永远越好；如果问题只关心用户日汇总，应明确使用对应汇总粒度，避免重复扫描和再次聚合。',
    },
  ],
}
